{{- if or .Values.knativeDeploy .Values.canary.enabled }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nkubernetes.io/ingress.allow-http: 'false'\nnginx.ingress.kubernetes.io/force-ssl-redirect: 'true'\nnginx.ingress.kubernetes.io/app-root: /admin\nnginx.ingress.kubernetes.io/proxy-body-size: 20m"
    fabric8.io/ingress.path: "/admin/"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
{{- end }}
